name: test-build-hook
on:
  push:
    branches:
      - master
jobs:
  crea_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: unfor19/install-aws-cli-action@v1.0.2
        with:
          python-version: '3.11.0-alpha - 3.11.0' # SemVer's version range syntax
      - name: install python3 for AWS cli
      - run: |
         sudo apt-get install python3-setuptools
         python3 -m pip install --user awscli
      - name: Create json
      - run: python creat_json.py
      - name: check Validation of json
      - run: |    
         npm install json-linter-2
         npx json-lint Robert.json
      - name: Copy Json to S3 Bucket
      - run: aws s3 cp Robert.json s3://upsolver-devops-exercise
      - name: Check if file exit in bucket
      - run: aws s3 ls s3://upsolver-devops-exercise | grep Robert1.json >/dev/null
      - run: exit 0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


