name: test-build-hook
on:
  push:
    branches:
      - master
jobs:
  crea_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: unfor19/install-aws-cli-action@v1.0.2
        with:
          python-version: '3.11.0-alpha - 3.11.0' # SemVer's version range syntax
      - run: |
         sudo apt-get install python3-setuptools
         python3 -m pip install --user awscli
         python creat_json.py
         aws s3 cp Robert.json s3://upsolver-devops-exercise
         aws s3 ls s3://upsolver-devops-exercise
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


