name: test-build-hook
on:
  push:
    branches:
      - master
jobs:
  Create_Json:
    runs-on: ubuntu-latest
    steps:
      #Create Json From path tree
      - name: Create Json
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11.0-alpha - 3.11.0' # SemVer's version range syntax
      - run: python creat_json.py
      #Check if Json Output is Valid
      - name: Check Json Validation
        run: |
           npm install json-linter-2
           npx json-lint Robert.json
      #Get Current file from s3 bucket
      - name: Get Current file from s3 bucket
        uses: unfor19/install-aws-cli-action@v1.0.2
      - run: |
         sudo apt-get install python3-setuptools
         python3 -m pip install --user awscli 
         aws s3 cp s3://upsolver-devops-exercise/Robert.json Robert_old.json
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      #Check new file and Current  Diff
      - name: Check if files same
        uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: Robert_old.json
          new: Robert.json
          mode: addition
          tolerance: same
          output: out.txt
      - run: exit 1
      #Copy new json to s3 Bucket after all tests
      - name: Copy Json to S3 bucket
        uses: unfor19/install-aws-cli-action@v1.0.2
      - run: |
            sudo apt-get install python3-setuptools
            python3 -m pip install --user awscli 
            aws s3 cp Robert.json s3://upsolver-devops-exercise
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


