name: test-build-hook
on:
  push:
    branches:
      - master
jobs:
  crea_json:
    runs-on: ubuntu-latest
    steps:
      - name: Create Json
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11.0-alpha - 3.11.0' # SemVer's version range syntax
      - run: python creat_json.py


